name: Build & Test

on:
  pull_request:
    branches: [master]

jobs:
  e2etests:
    if: github.event.pull_request.merged != true
    name: ${{ matrix.browser}} end-to-end tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [9.0]
        node: [20]
        browser: [chromium]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dotnet tools
        run: dotnet tool restore

      - name: Install C# dependencies
        run: dotnet restore

      - name: Run C# build
        run: dotnet build --no-restore

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./web

      - name: Install Playwright browsers
        run: npm run e2e:install
        working-directory: ./web

      - name: run end-to-end tests
        env:
          ASPNETCORE_URLS: http://localhost:5000
        run: npm run e2e
        working-directory: ./web
  build:
    name: Build ${{ matrix.os }} and Test
    if: github.event.pull_request.merged != true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [9.0]
        node: [20]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install node dependencies
        run: npm ci
        working-directory: ./web

      - name: Type check frontend
        run: npm run check-types
        working-directory: ./web

      - name: Type check E2E tests
        run: npm run check-types:e2e
        working-directory: ./web

      - name: Lint frontend
        run: npm run lint
        working-directory: ./web

      - name: Lint E2E tests
        run: npm run lint:e2e
        working-directory: ./web

      - name: Install dotnet tools
        run: dotnet tool restore

      - name: Install C# dependencies
        run: dotnet restore

      - name: Run C# build
        run: dotnet build --configuration Release --no-restore

      - name: Run C# tests
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./DigitalIcebreakers.Test
